name: stage codepush ios

on:
  push:
    branches:
      - "stage-push/ios"
jobs:
  stage-push-ios:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11']
    env:
      working-directory: ./ws/packages/unitz-mobile-advisor
      codepush-appname: Unitz/Unitz-Advisor-iOS
      codepush-deployment: Staging
    steps:
      @import stage_checkout
      @import ios_config
      @import yarn_install
      @import pod_install
      @import appcenter_release
      @import notify_status
