- uses: actions/cache@v2
  id: cachepods
  with:
    path: ${{env.working-directory}}/ios/Pods
    key: ${{ runner.os }}-${{ hashFiles('${{env.working-directory}}/ios/Podfile.lock') }}
- name: install pod
  working-directory: ${{env.working-directory}}
  if: steps.cachepods.outputs.cache-hit != 'true'
  run: |
    cd ios
    pod install
