- uses: actions/cache@v2
  id: cachenodemodules
  with:
    path: ${{env.working-directory}}/node_modules
    key: ${{ runner.os }}-${{ hashFiles('ws/yarn.lock') }}
- name: build modules
  working-directory: ${{env.working-directory}}
  if: steps.cachenodemodules.outputs.cache-hit != 'true'
  run: |
    yarn install
    yarn nuke:modules
