- name: check dir
  working-directory: ${{env.working-directory}}
  run: |
    pwd
    PWD=$(pwd)
    echo $PWD
- uses: actions/cache@v2
  id: cachenodemodules
  with:
    path: |
      ${{env.working-directory}}/node_modules
      ./ws/node_modules
    key: ${{ runner.os }}nodemodules-${{ hashFiles('ws/yarn.lock') }}
- name: build modules
  working-directory: ${{env.working-directory}}
  if: steps.cachenodemodules.outputs.cache-hit != 'true'
  run: |
    pwd
    yarn install
    yarn nuke:modules
