# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max",
  "iPhone 8 Plus",
  # "iPhone 8",
  # "iPhone SE",
  # "iPhone X",
  # "iPad Pro (12.9-inch)",
  "iPad Pro (9.7-inch)",
])

languages([
  "vi",
  # "en-US",
  # "de-DE",
  # "it-IT",
  # ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")
scheme("unitzmobileadvisorUITests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

workspace('./unitzmobileadvisor.xcworkspace')

# skip_open_summary(true)

derived_data_path('./fastlane/derived')

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

