# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase distribution"
  lane :stage do
    # increment_version_code(
    #   gradle_file_path: "app/build.gradle",
    #   ext_constant_name: "test"
    #   app_folder_name:"app"
    # )
    # android_set_version_code(
    #   version_code: 17, # optional, if not specified, Version Code will be incremented
    # )
    android_set_version_code(
      version_code: (Time.now.to_i() - 1577840400) / 100
    )
    gradle(task: "assembleRelease")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    android_set_version_code(
      version_code: (Time.now.to_i() - 1577840400) / 100
    )
    gradle(
      task: 'assemble',
      build_type: 'Release',
    )

    # crashlytics

    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      skip_upload_screenshots: true,
      skip_upload_images: true,
      apk: 'app/build/outputs/apk/release/app-release.apk',
    )
  
  end

  desc "Deploy a new version to the Google Play"
  lane :release do
    android_set_version_code(
      version_code: (Time.now.to_i() - 1577840400) / 100
    )
    gradle(
      task: 'assemble',
      build_type: 'Release',
    )
    upload_to_play_store(
      track: 'production',
      release_status: 'draft',
      apk: 'app/build/outputs/apk/release/app-release.apk',
    )
  end

  desc "Update appicon"
  lane :update_appicon do
    android_appicon(
      appicon_image_file: '../../../modules/unitz-assets/Icon.png',
      appicon_path: 'app/src/main/res/mipmap',
      generate_rounded: true
    )
  end
  
  desc "Update splash"
  lane :update_splash do
    android_appicon(
      appicon_image_file: '../../../modules/unitz-assets/splash.png',
      appicon_icon_types: %i[splash_port splash_land],
      appicon_path: 'app/src/main/res_t/drawable/splash',
      appicon_filename: 'splash'
    )
  end
end
