name: release android

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - "release/android"
    # tags:
    #   - "v*"
# defaults:
#   run:
#     working-directory: ./your_working_dir
jobs:
  release-android:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ws/packages/unitz-mobile
    steps:
      - name: setup node v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: clone workspace
        uses: actions/checkout@v2
        with:
          repository: Unitz-Co/ws-app-mobile
          path: ws
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true
      - name: clone env
        uses: actions/checkout@v2
        with:
          repository: Unitz-Co/env
          path: env
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true
      - name: clone credentials
        uses: actions/checkout@v2
        with:
          repository: Unitz-Co/credentials
          path: credentials
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - name: checkout submodule
        run: |
          cd ws
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.PAT_TOKEN }}:${{ secrets.PAT_TOKEN }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive
      - name: retrive certs and env
        working-directory: ${{env.working-directory}}
        run: |
          yarn config:android
      - name: build modules
        working-directory: ${{env.working-directory}}
        run: |
          yarn install
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: build android
        working-directory: ${{env.working-directory}}
        run: |
          cd android
          yarn build:android:release
